# base image
FROM gcr.io/google.com/cloudsdktool/google-cloud-cli:489.0.0-stable

# metadata
LABEL base.image="gcr.io/google.com/cloudsdktool/google-cloud-cli:489.0.0-stable"
LABEL dockerfile.version="2"
LABEL software="WAPHL-Terra2AWS"
LABEL software.version="v1.0.0"
LABEL description="Basic requirements for running WAPHL-Terra2AWS"
LABEL website="https://github.com/DOH-JDJ0303/waphl-terra2aws"
LABEL license="Apache 2.0"
LABEL maintainer="Jared Johnson"
LABEL maintainer.email="jared.johnson@doh.wa.gov"

# prevents having to enter commands during apt-get install
ENV DEBIAN_FRONTEND=noninteractive

# install dependencies
RUN apt-get update && apt-get -y --no-install-recommends install \
    ca-certificates \
    libssl-dev \
    zlib1g-dev \
    libbz2-dev \
    libreadline-dev \
    libsqlite3-dev \
    make \
    llvm \
    libncurses5-dev \
    libncursesw5-dev \
    xz-utils \
    tk-dev \
    libffi-dev \
    liblzma-dev \
    build-essential \
    bc \
    unzip \
    tar \
    gzip \
    curl \
    wget \
    python3-all \
    python-is-python3 \
    python3-pip \
    pipx \
    bzip2 && \
    apt-get autoclean && \
    rm -rf /var/lib/apt/lists/*

RUN apt-get update && apt-get install -y procps && rm -rf /var/lib/apt/lists/*

# required Python modules
RUN pip3 install firecloud tqdm --break-system-packages